### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by nihalpawar4** [adrianhajdin/project_professional_portfolio#57]
When I click on navbar it's quite flickering on my system also tried with other browers and devices it's same problem

**Comment by nihalpawar4** [comment]
Look into this

**Comment by jenperez613** [comment]
try adding this in Navbar.jsx after the first <ul>: 

<div className='app__navbar-menu'>
        <HiMenuAlt4 onClick={() => setToggle(true)} />
        {toggle && (
          <motion.div
            **style={{ opacity: 0 }}**
            **whileInView={{ x: [300, 0], opacity: [0.9, 1] }}**
            transition={{ duration: 0.85, ease: 'easeOut' }}>
            <HiX onClick={() => setToggle(false)} />
            <ul>

**Comment by mohitmk007** [comment]
that's great.

**Comment by nihalpawar4** [comment]
seems cool
